version: "3.4"

services:
  backend:
    build: 
      context: ./backend
      args:
        - PORT=${PORT:-8080}
    container_name: taxi_cab_booking_backend
    ports:
      - ${HOST_PORT:-8080}:${PORT:-8080}
